[package]
name = "equator"
version = "0.0.1"
authors = ["Callum Tolley <cgtrolley@gmail.com>"]

[dependencies]
gtk = "0.0.6"
gtk-sys = "0.2.1"
gdk = "0.2.0"
cairo-rs = "0.0.7"
#decimal = "0.1.2"

[dependencies.decimal]
#git = "https://github.com/trolleyman/decimal"
path = "S:/Downloads/decimal"
