[package]
name = "equator"
version = "0.0.1"
authors = ["Callum Tolley <cgtrolley@gmail.com>"]

[dependencies]
gdk = "*"
cairo-rs = "*"
decimal = "*"
lazy_static = "*"

[dependencies.gtk]
version = "*"
features = ["v3_22"]

[target.'cfg(windows)'.dependencies]
kernel32-sys = "*"
